import Link from "next/link";
import { addProvenanceAction, createContradictionAction, createEntityAction, disposeContradictionAction, linkClaimsAction, reviewClaimAction, saveResearchViewAction } from "./actions";
import { EventRow, EvidenceCard, MonoLabel, SpecRow, Wordmark } from "./casework-ui";
import { TestimonyIntakeForm } from "./testimony-intake-form";
import { TestimonySourceReader } from "./testimony-source-reader";
import { signOut } from "./login/actions";
import { requireCaseActor } from "@/lib/authority";
import { getTestimonyIntakeWorkspace, getWorkspace } from "@/lib/casework-supabase";
import { formatSourceLocator } from "@/lib/source-locator";
import { windowsForEvent } from "@/lib/timeline";

export const dynamic = "force-dynamic";

export default async function Home({ searchParams }: { searchParams: Promise<{ view?: string }> }) {
  const actor = await requireCaseActor();
  const workspace = await getWorkspace(actor);
  const testimony = await getTestimonyIntakeWorkspace(actor);
  const { view: selectedViewId } = await searchParams;
  const selectedView = workspace.savedViews.find((view) => view.id === selectedViewId);
  const pending = workspace.claims.filter((claim) => claim.status === "candidate").slice(0, 20);
  const candidateCount = workspace.claims.filter((claim) => claim.status === "candidate").length;
  const timeline = workspace.claims.filter((claim) => claim.event_title);
  const windowed = {
    ninety_days: timeline.filter((item) => windowsForEvent(item.event_time_start, workspace.incidentAt, workspace.incidentWindowStart, workspace.incidentWindowEnd).includes("ninety_days")),
    thirty_days: timeline.filter((item) => windowsForEvent(item.event_time_start, workspace.incidentAt, workspace.incidentWindowStart, workspace.incidentWindowEnd).includes("thirty_days")),
    incident_window: timeline.filter((item) => windowsForEvent(item.event_time_start, workspace.incidentAt, workspace.incidentWindowStart, workspace.incidentWindowEnd).includes("incident_window")),
  };
  const visibleWindows = selectedView && selectedView.research_window !== "all" ? [selectedView.research_window as keyof typeof windowed] : (["ninety_days", "thirty_days", "incident_window"] as const);
  const visibleContradictions = selectedView?.include_unresolved === false ? workspace.contradictions.filter((item) => item.status !== "unresolved") : workspace.contradictions;
  const unresolvedCount = visibleContradictions.filter((item) => item.status === "unresolved").length;

  return <main className="casework-shell">
    <header className="masthead">
      <Wordmark />
      <nav aria-label="Workspace modes"><Link href="/search">Search testimony</Link><a href="/compiler">Testimony Compiler</a><a href="#dossier">Dossier / Paper</a><a href="#console">Console</a></nav>
      <div className="account"><span>{actor.email}</span><form action={signOut}><button className="text-button">Sign out</button></form></div>
    </header>

    <section className="case-header">
      <div><MonoLabel>ACTIVE CASE · PRIVATE WORKSPACE</MonoLabel><h1>{workspace.caseTitle}</h1><p>Source-grounded reconstruction. Record integrity, evidentiary assessment, and extraction confidence remain independent.</p></div>
      <div className="case-metrics" aria-label="Case corpus totals">
        <div><strong>{testimony.counts.intakes}</strong><span>URL captures</span></div><div><strong>{testimony.counts.segments}</strong><span>Segments</span></div><div><strong>{testimony.counts.claims}</strong><span>Assertions</span></div><div className={testimony.counts.acquisitionTargets > 0 ? "attention" : ""}><strong>{testimony.counts.acquisitionTargets}</strong><span>Acquisition gaps</span></div>
      </div>
    </section>

    <section className="workspace-mode dossier-mode" id="dossier">
      <header className="mode-heading"><div><MonoLabel>DOSSIER / PAPER</MonoLabel><h2>Read the source. Inspect the chain.</h2></div><p>Source Reader · Sources · Entities · Chronology · Evidence inspection</p></header>
      <div className="source-intake-grid" id="sources">
        <div className="source-intake-panel"><header className="panel-heading"><div><MonoLabel>SOURCE INTAKE</MonoLabel><h2>Capture testimony</h2></div><span>Public or authorized material only</span></header><TestimonyIntakeForm /></div>
        <aside className="source-register"><header className="panel-heading"><div><MonoLabel>SOURCE REGISTRY</MonoLabel><h2>Captured sources</h2></div><span>{testimony.intakes.length} records</span></header>
          {testimony.intakes.length === 0 ? <p className="paper-empty">No testimony source captured.</p> : testimony.intakes.map((intake) => <article className="source-specimen" key={intake.id}><div className="source-specimen-title"><span className={`record-chip${intake.exact_duplicate_of ? " attention" : ""}`}>{intake.exact_duplicate_of ? "EXACT DUPLICATE" : intake.processing_status.toUpperCase()}</span><strong>{intake.page_title ?? "Captured testimony page"}</strong></div><div className="spec-table"><SpecRow label="PUBLISHER" value={intake.publisher ?? "UNKNOWN"} /><SpecRow label="PUBLISHED" value={intake.published_date ?? "UNKNOWN"} /><SpecRow label="CAPTURED" value={new Date(intake.captured_at).toLocaleString()} /><SpecRow label="SHA-256" value={`${intake.sha256.slice(0, 20)}…`} accent /><SpecRow label="CANONICAL" value={intake.canonical_url ? <a href={intake.canonical_url} target="_blank" rel="noreferrer">OPEN SOURCE →</a> : "URL NOT RECORDED"} last /></div></article>)}
          {testimony.media.map((media) => <EvidenceCard tag={media.provider.toUpperCase()} title={media.artifact_title} relation={media.possessed_by_us ? "POSSESSED MEDIA" : "EXTERNAL REFERENCE ONLY"} meta={media.external_id ?? "IDENTIFIER UNAVAILABLE"} key={media.id} />)}
        </aside>
      </div>

      <TestimonySourceReader segments={testimony.segments} qaExchanges={testimony.qaExchanges} candidates={testimony.candidates} reviewVersions={testimony.reviewVersions} acquisitions={testimony.acquisitions} />

      <section className="paper-subsection" id="timeline"><header className="section-heading"><div><MonoLabel>CHRONOLOGY</MonoLabel><h2>Reviewed events retain their origin.</h2></div><span>{timeline.length} reviewed events</span></header>
        {selectedView ? <div className="active-view">ACTIVE VIEW · <strong>{selectedView.name}</strong> · {selectedView.include_unresolved ? "UNRESOLVED SHOWN" : "RESOLVED ONLY"}<Link href="/">CLEAR VIEW →</Link></div> : null}
        {timeline.length === 0 ? <div className="paper-empty">The chronology remains empty until a human review decision admits a distinct event.</div> : <div className={`chronology-grid lanes-${visibleWindows.length}`}>{visibleWindows.map((window) => <div className="chronology-lane" key={window}><header><MonoLabel>{window.replaceAll("_", " ")}</MonoLabel><strong>{windowed[window].length}</strong></header>{windowed[window].map((item, index) => <EventRow reference={`EVT-${String(index + 1).padStart(3, "0")}`} date={item.event_time_start ? new Date(item.event_time_start).toLocaleDateString("en-US", { month: "short", day: "2-digit", year: "numeric", timeZone: "UTC" }) : "UNKNOWN"} title={item.event_title ?? "Untitled event"} meta={`${(item.time_precision ?? "unknown").toUpperCase()} · ${item.artifact_title}`} key={`${window}-${item.id}`} />)}</div>)}</div>}
        <form action={saveResearchViewAction} className="instrument-form view-form"><h3>Save reconstruction view</h3><label>View name<input name="name" required placeholder="Final 30 days — unresolved included" /></label><label>Research window<select name="researchWindow"><option value="all">All events</option><option value="ninety_days">90 days</option><option value="thirty_days">30 days</option><option value="incident_window">Incident window</option></select></label><label className="check-label"><input type="checkbox" name="includeUnresolved" defaultChecked /> Include unresolved items</label><button>Save view</button></form>
        {workspace.savedViews.length > 0 ? <div className="view-links">{workspace.savedViews.map((view) => <Link className={view.id === selectedViewId ? "active" : ""} href={`/?view=${view.id}#timeline`} key={view.id}>{view.name}<small>{view.research_window.replaceAll("_", " ")}</small></Link>)}</div> : null}
      </section>

      <section className="paper-subsection" id="entities"><header className="section-heading"><div><MonoLabel>ENTITIES + PROVENANCE</MonoLabel><h2>Name the actors without erasing the record.</h2></div><span>{workspace.entities.length} durable entities</span></header>
        <div className="two-column-grid"><form action={createEntityAction} className="instrument-form"><h3>Create durable entity</h3><label>Canonical name<input name="canonicalName" required placeholder="Person, institution, device, or place" /></label><label>Kind<select name="kind"><option value="person">Person</option><option value="organization">Organization</option><option value="location">Location</option><option value="device">Device</option><option value="proceeding">Legal proceeding</option><option value="system_node">System node</option></select></label><label>Source-specific aliases<input name="aliases" placeholder="Comma-separated; original wording retained" /></label><label>Description<textarea name="description" rows={3} placeholder="Neutral identity note, not a credibility judgment" /></label><button>Create entity</button></form><div className="registry-list"><h3>Entity registry</h3>{workspace.entities.length === 0 ? <p className="paper-empty">No durable entities yet.</p> : workspace.entities.map((entity) => <article key={entity.id}><MonoLabel>{entity.kind.replaceAll("_", " ")}</MonoLabel><strong>{entity.canonical_name}</strong>{entity.aliases.length > 0 ? <p>Also recorded as: {entity.aliases.join(", ")}</p> : null}<small>{entity.description}</small></article>)}</div></div>
        {workspace.artifacts.length > 0 && workspace.entities.length > 0 ? <form action={addProvenanceAction} className="instrument-form inline-instrument"><h3>Attach provenance role</h3><select name="artifactId" aria-label="Provenance artifact">{workspace.artifacts.map((artifact) => <option key={artifact.id} value={artifact.id}>{artifact.title}</option>)}</select><select name="entityId" aria-label="Provenance entity">{workspace.entities.map((entity) => <option key={entity.id} value={entity.id}>{entity.canonical_name}</option>)}</select><select name="role" aria-label="Provenance role"><option value="originator">Originator</option><option value="publisher">Publisher</option><option value="custodian">Custodian</option><option value="submitter">Submitter</option></select><input name="note" aria-label="Provenance note" placeholder="Optional qualification" /><button>Add role</button></form> : null}
        {workspace.provenance.length > 0 ? <div className="provenance-grid">{workspace.provenance.map((item, index) => <article key={`${item.artifact_title}-${item.role}-${index}`}><MonoLabel>{item.role}</MonoLabel><strong>{item.canonical_name}</strong><p>{item.artifact_title}</p></article>)}</div> : null}
      </section>
    </section>

    <section className="workspace-mode console-mode" id="console"><header className="mode-heading"><div><MonoLabel>CONSOLE</MonoLabel><h2>Resolve what requires a human.</h2></div><p>Human Review · Unresolved attribution · Acquisition queue · Conflicts · Reconciliation</p></header>
      <div className="console-overview"><div><MonoLabel>REVIEW QUEUE</MonoLabel><strong>{candidateCount}</strong><span>candidate assertions</span></div><div className={testimony.acquisitions.length > 0 ? "attention" : ""}><MonoLabel>ACQUISITION QUEUE</MonoLabel><strong>{testimony.acquisitions.length}</strong><span>known gaps</span></div><div className={unresolvedCount > 0 ? "attention" : ""}><MonoLabel>UNRESOLVED CONFLICTS</MonoLabel><strong>{unresolvedCount}</strong><span>open tensions</span></div><div><MonoLabel>ASSESSMENT</MonoLabel><strong className="word-value">UNASSESSED</strong><span>not inferred from confidence</span></div></div>

      <section className="console-subsection acquisition-console"><header className="console-section-heading"><div><MonoLabel>ACQUISITION QUEUE</MonoLabel><h2>Known evidence is not possessed evidence.</h2></div><span>{testimony.acquisitions.length} targets</span></header><div className="acquisition-grid">{testimony.acquisitions.length === 0 ? <p className="console-empty">No acquisition gaps identified.</p> : testimony.acquisitions.map((target) => <article key={target.id}><div><span className="attention-marker">{target.priority.toUpperCase()} PRIORITY</span><strong>{target.title}</strong><p>{target.known_to_exist ? "KNOWN TO EXIST" : "EXISTENCE UNCONFIRMED"} · {target.possessed_by_us ? "POSSESSED" : "NOT POSSESSED"} · {target.admitted_as_exhibit === null ? "ADMISSION UNKNOWN" : target.admitted_as_exhibit ? "ADMITTED" : "NOT ADMITTED"}</p></div>{target.deep_link ? <a href={target.deep_link} target="_blank" rel="noreferrer">OPEN DISCOVERY TIMESTAMP →</a> : null}</article>)}</div></section>

      <section className="console-subsection review-console"><header className="console-section-heading"><div><MonoLabel>HUMAN REVIEW</MonoLabel><h2>Claims do not become events by default.</h2></div><span>{pending.length} displayed of {candidateCount}</span></header>{pending.length === 0 ? <div className="console-empty">No claims await review.</div> : <div className="review-queue">{pending.map((claim) => <article className="review-record" key={claim.id}><header><span className="attention-marker">CANDIDATE ASSERTION</span><strong>{claim.claimant}</strong><small>{claim.artifact_title} · {formatSourceLocator(claim.locator)}</small></header><blockquote>{claim.exact_text}</blockquote><p>{claim.assertion}</p><form action={reviewClaimAction} className="console-form"><input type="hidden" name="claimId" value={claim.id} /><label>Reviewed event title<input required name="eventTitle" placeholder="Describe the supported occurrence without overclaiming" /></label><label>Time precision<select name="precision" defaultValue="unknown"><option value="exact">Exact</option><option value="approximate">Approximate</option><option value="interval">Interval</option><option value="relative">Relative</option><option value="unknown">Unknown</option></select></label><label>Interval end<input type="datetime-local" name="eventTimeEnd" /></label><label>Uncertainty note<input name="uncertaintyNote" placeholder="What remains imprecise or contested?" /></label><label className="wide">Review rationale<textarea required name="rationale" rows={2} placeholder="Why does the evidence support a distinct reviewed event?" /></label><button>Accept claim + create event</button></form></article>)}</div>}</section>

      <section className="console-subsection" id="analysis"><header className="console-section-heading"><div><MonoLabel>LINEAGE + CONFLICTS</MonoLabel><h2>Repetition is not corroboration.</h2></div><span>Reconciliation remains explicit</span></header>{workspace.claims.length < 2 ? <div className="console-empty">Add a second claim to trace lineage or conflict.</div> : <div className="console-form-grid"><form action={linkClaimsAction} className="console-form"><h3>Trace claim lineage</h3><label>Origin / parent claim<select name="parentClaimId">{workspace.claims.map((claim) => <option key={claim.id} value={claim.id}>{claim.assertion}</option>)}</select></label><label>Downstream claim<select name="childClaimId">{workspace.claims.map((claim) => <option key={claim.id} value={claim.id}>{claim.assertion}</option>)}</select></label><label>Relationship<select name="kind"><option value="repeats">Repeats</option><option value="quotes">Quotes</option><option value="paraphrases">Paraphrases</option><option value="derives_from">Derives from</option><option value="origin">Independent origin</option></select></label><label>Reasoning<textarea required name="rationale" rows={3} placeholder="What in the record establishes this lineage?" /></label><button>Record lineage</button></form><form action={createContradictionAction} className="console-form attention-form"><h3>Open evidentiary tension</h3><label>Title<input required name="title" placeholder="Accounts conflict on timing" /></label><label>First claim<select name="firstClaimId">{workspace.claims.map((claim) => <option key={claim.id} value={claim.id}>{claim.assertion}</option>)}</select></label><label>Second claim<select name="secondClaimId">{workspace.claims.map((claim) => <option key={claim.id} value={claim.id}>{claim.assertion}</option>)}</select></label><label>Description<textarea required name="description" rows={3} placeholder="Describe the incompatibility without forcing resolution." /></label><button>Keep conflict unresolved</button></form></div>}
        <div className="console-results"><div><h3>Lineage register</h3>{workspace.lineage.length === 0 ? <p className="console-muted">No source dependency recorded.</p> : workspace.lineage.map((edge, index) => <article key={index}><MonoLabel>{edge.kind.replaceAll("_", " ")}</MonoLabel><p>{edge.parent_assertion}</p><b aria-hidden="true">↓</b><p>{edge.child_assertion}</p><small>{edge.rationale}</small></article>)}</div><div><h3>Conflict register</h3>{visibleContradictions.length === 0 ? <p className="console-muted">No conflicts match the active view.</p> : visibleContradictions.map((item) => <article className="conflict-record" key={item.id}><span className={item.status === "unresolved" ? "attention-marker" : "record-chip"}>{item.status.toUpperCase()}</span><strong>{item.title}</strong><p>{item.description}</p><small>{item.claim_count} linked claims{item.status === "unresolved" ? " · closure requires disposition evidence" : ` · ${item.disposition_rationale}`}</small>{item.status === "unresolved" ? <form action={disposeContradictionAction} className="console-form disposition-form"><input type="hidden" name="contradictionId" value={item.id} /><select name="disposition" aria-label={`Disposition for ${item.title}`}><option value="resolved_by_evidence">Resolved by evidence</option><option value="clarified">Clarified</option><option value="superseded">Superseded</option><option value="cancelled">Cancelled</option></select><select name="evidenceClaimId" aria-label={`Disposition evidence for ${item.title}`}><option value="">No evidence claim (cancellation only)</option>{workspace.claims.map((claim) => <option key={claim.id} value={claim.id}>{claim.assertion}</option>)}</select><textarea name="rationale" required rows={2} aria-label={`Disposition rationale for ${item.title}`} placeholder="State the terminal condition and observable evidence." /><button>Record terminal disposition</button></form> : null}</article>)}</div></div>
      </section>

      <section className="console-subsection authority-console"><header className="console-section-heading"><div><MonoLabel>AUTHORITY LOG</MonoLabel><h2>Consequential changes leave a trail.</h2></div><span>{workspace.audit.length} recent entries</span></header><div className="audit-list">{workspace.audit.map((event, index) => <div key={index}><time>{new Date(event.occurred_at).toLocaleString("en-US", { dateStyle: "medium", timeStyle: "short" })}</time><strong>{event.action.replaceAll(".", " · ")}</strong><span>{event.subject_type}</span></div>)}</div></section>
    </section>

    <footer><Wordmark /><p>Candidate ≠ fact · Record state ≠ evidentiary assessment · Confidence ≠ verification</p></footer>
  </main>;
}
